name: StaffStatus
main: jaylac2000\Staff\Main
api: 3.0.0
description: "/staff command"
version: 1.0.0
author: jaylac2000
website: https://github.com/jaylac2000

commands:
  staff:
    description: List the staff
