name: StaffStatus  
main: jaylac2000\StaffStatus\Main
api: 3.0.0
description: "display your staffs status"
version: 1.0.2
author: jaylac2000
website: https://github.com/jaylac2000

commands:
  staff:
    description: List the staff
  invisible:
    description: "Enter invisible mode"
    permission: "invis.use"
    aliases:
    - invis
permissions:
  invis.use:
    description: "Permission to enter invisible mode"
    default: op
  invis.see:
     description: "Permission to see invisible players"
     default: op
