name: StaffList
main: jaylac2000\StaffList\Main
api: 3.0.0
description: "display the status of your staff"
version: 1.0.1
author: jaylac2000 
website: https://github.com/jaylac2000
web: https://apollomcpe.xyz/ uh test...

commands:
  staff:
    description: List the staff
