name: StaffStatus
main: Staff\Main
api: 3.0.0
description: /staff command.
version: 1.0.0
author: jaylac2000
website: https://github.com/jaylac2000
# This plugin is out of my servers core

commands:
  staff:
    description: List the staff
