# Note: You can add as many as you want
# /staff will display IGN: online/offline status
# When adding a name, it must be their exact name including caps
 
staff:
  - jaylac2000 # my IGN : you may remove it
  - JayzCraftYT # my second account : you may remove it
  - YourNameHere
  - AnotherNameHere
  - Etc

# -----------------------------------------------------------------
 
# Use the § symbol for color coding
# Use %name for getting a players name

# The message that will be sent to online players when you will activate invisibility mode
enable-leave: false
FakeLeave: "§e%name §l§d[§4-§d]" # THIS IS MY LEAVE MESSAGE, CHANGE IT TO YOURS!!

# The message that will be sent to online players when you will deactivate invisibility mode
enable-join: false
FakeJoin: "§e%name §l§d[§2+§d]" # THIS IS MY JOIN MESSAGE, CHANGE IT TO YOURS!!
...