# Note: You can add as many as you want
# /staff will display IGN: online/offline status
# When adding a name, it must be their exact name including caps

# ----- Staff Status Names -----

staff:
  - jaylac2000 # my IGN : you may remove it
  - JayzCraftYT # my second account : you may remove it
  - YourNameHere
  - AnotherNameHere
  - Etc

# ----------Invisible-----Stuff-----Settings----------
...